ignore:
  - "inventree_mcp/test_mcp.py"

coverage:
  status:
    project:
      default:
        target: 90%
    patch:
      default:
        target: 95%

github_checks:
  annotations: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: integration-tests
      carryforward: true
      statuses:
        - type: project
          target: 90%
